// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Terence1105/hexagonal/account/adapter/in"
	"github.com/Terence1105/hexagonal/account/adapter/out"
	"github.com/Terence1105/hexagonal/account/application/service"
)

// Injectors from wire.go:

func InitializeGinAdapter() in.GinAdapter {
	iTransferPort := out.NewAccountLevelDBAdapter()
	iTransferUseCase := service.NewTransferService(iTransferPort)
	ginAdapter := in.NewGinAdapter(iTransferUseCase)
	return ginAdapter
}

func InitializeFiberAdapter() in.FiberAdapter {
	iTransferPort := out.NewAccountLevelDBAdapter()
	iTransferUseCase := service.NewTransferService(iTransferPort)
	fiberAdapter := in.NewFiberAdapter(iTransferUseCase)
	return fiberAdapter
}
